language: cpp
sudo: required
dist: trusty
compiler:
- g++
install:
  - sudo apt-get install libwxgtk3.0-dev libwxgtk3.0-0-dbg -y
script:
  - ./autogen.sh    
  - mkdir $PWD/build
  - ./configure --prefix=$PWD/build
  - make -j4
  - make all install
  - ls -lt $PWD/build/bin/gamessq

# turn off email notifications
notifications:
  email: false
